server:
  port: 8082

spring:
  application:
    name: HOTEL-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel-service
    username: postgres
    password: 1212
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# spring eureka configurations

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
