server:
  port: 8761

spring:
  application:
    name: SERVICE-REGISTRY
  config:
    import: optional:configserver:http://localhost:8085

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
