server:
  port: 8081

spring:
  # Eureka server is fetch the name by-default so don't use this
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/user-service
    username: root
    password: 1212
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

# by default true rahta h
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka